Comma separate minified array items
Currently a minified array will be output as

```
{"version":"0.14.3","members":[{"name":"Uttra","level":1,"cclass":"Knight"}{"name":"Cathal","level":1,"cclass":"Cleric"}{"name":"Gerard","level":1,"cclass":"Hunter"}{"name":"Aife","level":1,"cclass":"Mage"}],"silver":2000}
```

This is not valid JSON due to missing commas betwixt array items:

```
Error: Parse error on line 1:
...1,"cclass":"Knight"}{"name":"Cathal","le
-----------------------^
Expecting 'EOF', '}', ',', ']', got '{'
```